// Code generated by github.com/kanryu/validagen. DO NOT EDIT.
package example

import (
	"regexp"
	"github.com/go-ozzo/ozzo-validation/v4/is"
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Validate validater for Address struct
func (a Address) Validate() error {
	return validation.ValidateStruct(&a,
		validation.Field(&a.Food, validation.In("Cheeze", "Milk", "Meat"), validation.Required),
		validation.Field(&a.Income, validation.In(1.1, 2.2, 3.3), validation.Required),
		validation.Field(&a.Mail, validation.Required, is.Email),
		validation.Field(&a.People, validation.In(1, 2, 3), validation.Required),
		validation.Field(&a.State, validation.Match(regexp.MustCompile("^[A-Z]{2}$")), validation.Required),
		validation.Field(&a.Street, validation.Length(5,50), validation.Required),
	)
}
