// Code generated by github.com/kanryu/validagen. DO NOT EDIT.
package example


import (
	"testing"
)

// TestAddress_Validate a test suite for (a *Address)Validate()
func TestAddress_Validate(t *testing.T) {
	tests := []struct {
		name    string
		a       Address
		wantErr bool
	}{
		{wantErr: false, name: "OK", a: Address{Food:"Cheeze",Income:2.2,Mail:"ab@example.com",People:3,State:"SF",Street:"street"}},
		{wantErr: true, name: "NG for Food", a: Address{Food:"Cheezended",Income:2.2,Mail:"ab@example.com",People:3,State:"SF",Street:"street"}},
		{wantErr: true, name: "NG for Income", a: Address{Food:"Cheeze",Income:2.233,Mail:"ab@example.com",People:3,State:"SF",Street:"street"}},
		{wantErr: true, name: "NG for Mail", a: Address{Food:"Cheeze",Income:2.2,Mail:"nil",People:3,State:"SF",Street:"street"}},
		{wantErr: true, name: "NG for People", a: Address{Food:"Cheeze",Income:2.2,Mail:"ab@example.com",People:33,State:"SF",Street:"street"}},
		{wantErr: true, name: "NG for State", a: Address{Food:"Cheeze",Income:2.2,Mail:"ab@example.com",People:3,State:"SFX",Street:"street"}},
		{wantErr: true, name: "NG for Street", a: Address{Food:"Cheeze",Income:2.2,Mail:"ab@example.com",People:3,State:"SF",Street:"fail"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.a.Validate()
			if tt.wantErr {
				if err == nil {
					t.Fatalf("%q. wantErr %v, but actual err %v", tt.name, tt.wantErr, err)
				}
			} else if err != nil {
				t.Fatalf("%q. wantErr %v, but actual err occured %+v", tt.name, tt.wantErr, err)
			}
		})
	}
}

